### ISSUE TITLE
endpointURL

### ISSUE THREAD

**Issue by smrgeoinfo** [webapi-discovery/rfcs#14]
what is the use case for 'endpointUrl' at the WebAPI level.  If the  API offers different resources they will likely have path extensions on the base endpointUrl. It makes more sense to me to indicate the target/entryPoint/urlTemplate for each potentialAction. The urlTemplates could use paths relative to the urlTemplate, but there needs to be some clear, documented convention if this is the standard interpretation.

**Comment by MikeRalphson** [comment]
As described, this is simply "The root location or primary endpoint of the API." Resources exposed by the API would be described by the linked machine-readable documentation. Hypermedia APIs would not necessarily need to expose such separate documentation beyond the root URL (which must be 'discoverable by some mechanism', paraphrasing Fielding).
