### ISSUE TITLE
Remove version property

### ISSUE THREAD

**Issue by nickevansuk** [webapi-discovery/rfcs#16]
There was quite a bit of contention around including `softwareVersion` in the last round of iterations:
https://github.com/schemaorg/schemaorg/pull/1445#issuecomment-265560356

Perhaps, for the same reasons as described there, we should remove it from our draft?

**Comment by MikeRalphson** [comment]
Contention rather than consensus I would say. I'd prefer to leave it in the draft for now, as this is a proposed extension to the MVP WebApi schema.org initially went with. They're not beholden to take everything here en-masse.

**Comment by nickevansuk** [comment]
Sure sounds good
