### ISSUE TITLE
OpenAPI / Swagger in YAML Media Type

### ISSUE THREAD

**Issue by kinlane** [webapi-discovery/rfcs#2]
Is the OpenAPI / Swagger in YAML under 2.1. Content-Types intentionally a duplicate of OpenAPI / Swagger in JSON, or is just copy / paste mistake? 

Currently is: OpenAPI / Swagger in YAML | application/openapi+json or application/x-openapi+json

**Comment by MikeRalphson** [comment]
You're right, it's a copy and paste error.

This is one of the areas which needs updating for the next draft. 

In https://github.com/OAI/OpenAPI-Specification/issues/110#issuecomment-364498200 @darrelmiller has proposed the following:

* `application/vnd.oai.openapi` for the YAML variant
* `application/vnd.oai.openapi+json` for the JSON only variant 

Once these are approved I will update the draft.

Thanks for pointing it out.

**Comment by kinlane** [comment]
Figured that was the case.  We just need @darrelmiller to get to work on a media type for YAML! ;-)

**Comment by MikeRalphson** [comment]
Re-opening to remind me to action.

**Comment by MikeRalphson** [comment]
Updated with proposed/approved content-types.
